version: '3.4'

services:
  stock:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    command: >
      /bin/sh -c 
      '
      echo "db is preparing!";
      sleep 20;

      echo "db is ready!";
      node trade_history.js
      '
  mongodb:
    image: mongo
    ports:
    - 27018:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
    - /Users/jo1ce/Documents/docker/data/db:/data/db
  mongo-express:
    image: mongo-express
    ports:
    - 8080:8081
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
    - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    - ME_CONFIG_MONGODB_SERVER=mongodb
